### ISSUE TITLE
Version 3.0

### ISSUE THREAD

**Issue by lpeyr** [Leo-Corporation/Generateur-de-mots-de-passe#18]
# Version 3.0
## 1. Introduction
Générateur de mots de passe est un logiciel qui permet de générer des mots de passe simplement.
Dans un logiciel, l'interface utilisateur est un point clé : elle doit être simple à comprendre pour l'utilisateur et jolie.
Actuellement, l'interface de Générateur de mots de passe respecte certains de ces critères, mais elle n'est plus très à la page.
C'est pour cela que la version 3.0 de Générateur de mots de passe devra comporter une meilleure interface.
## 2. Guna.UI
La version 3.0 utilisera un "framework de design" qui est [Guna.UI](https://github.com/sobatdata/Guna.UI-Framework-Lib).
Guna.UI permet de designer une interface utilisateur simplement en .NET Framework.
Le framework contient de nombreux contrôles intéressants comme : 
- GunaAdvenceButton
- GunaAdvenceTileButton
- GunaDragControl
- GunaElipse
- GunaControlBox
- GunaTextBox
- GunaShadowForm
- etc...
## 3. "Cahier des charges"
Cette version 3.0 devra comporter des changements majeurs liés à l'interface.
Voici donc "To Do List" des changements à effectuer : 
- [x] Ajouter Guna.UI (#21)
- [x] Embellir l'interface (#22)
- [x] Ajouter le contrôle "GunaShadowForm" (#23)
- [x] Ajouter le contrôle "GunaElipse" (#23)
- [x] Rendre le thème sombre compatible (#24)
- [x] Modifier la propriété `FormBorderStyle` à `None` (#23)
- [x] Ajouter le contrôle GunaDragControl (#23)
- [x] Ajouter le contrôle GunaControlBox (Close & minimize)(#23)
- [x] Ajouter un préréglage personnalisable (#28)
- [x] Définir un préréglage par défaut (#29)
- [x] Pour voir réinitialiser le logiciel + paramètres (#30)
- [x] ...
Cette liste pourra être modifiée à tout moment.

**Comment by lpeyr** [comment]
**Stade final** : Le logiciel est prêt à être sorti.
